name: Carbon Aware Demo

on:
  push:
    branches: [ main ]

permissions:
  contents: write   # ✅ Needed for GitHub Pages deployment

jobs:
  carbon-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests
      - run: python carbon_check.py

  deploy:
    needs: carbon-check
    if: success()   # only run if carbon_check.py exits with 0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
